#services:
#   minio:
#     image: quay.io/minio/minio
#     container_name: minio
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     environment:
#       MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#       MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#     volumes:
#       - ./minio-data:/data
#     command: server /data --console-address ":9001"
#     networks:
#       - airbyte-net

# networks:
#   minio-net:
#     driver: bridge


services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ${HOME}/minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - airbyte-net

  postgres-destination:
    image: debezium/postgres:13
    container_name: postgres-destination
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DESTINATION_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DESTINATION_USER}
      POSTGRES_DB: ${POSTGRES_DESTINATION_DB_NAME}
    ports:
      - "4000:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks: 
      - airbyte-net

  # dbt for local development and testing, should be overriden
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt
    working_dir: /app
    volumes:
      - ./dbt:/app       # <-- project code and models synced with the container
      - ~/.dbt:/root/.dbt # <-- user config and credentials synced with the container
    ports:
      - "8085:8080"
    tty: true
    networks:
      - airbyte-net
    depends_on:
      - postgres-destination

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "my_super_secret_key_12345"  # Cambia esto por algo más seguro
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - postgres-destination
    command: >
      /bin/sh -c "
      pip install psycopg2-binary &&
      superset db upgrade &&
      superset fab create-admin --username admin --password admin --firstname Superset --lastname Admin --email admin@example.com || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - airbyte-net

volumes:
  pg_data:
  superset_home:

networks:
  airbyte-net:
    external: true



  

#   postgres:
#     image: debezium/postgres:13
#     container_name: postgres-destination
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: posgresadmin
#       POSTGRES_DB: postgres
#     ports:
#       - "4000:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     networks:
#       - airbyte-net

#   minio:
#     image: quay.io/minio/minio
#     container_name: minio
#     restart: always
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: minioadmin123
#     volumes:
#       - minio-data:/data
#     command: server /data --console-address ":9001"
#     networks:
#       - airbyte-net

# volumes:
#   minio-data:
#   pg_data:


