version: 2

models:
  - name: silver
    description: "Silver model containing cleaned ship positions with transformed ETA and ship type info"
    columns:
      - name: user_id
        description: "User identifier"
        tests:
          - not_null

      - name: name
        description: "Name of the ship"
        tests:
          - not_null

      - name: imo_number
        description: "IMO number of the ship"
        tests:
          - not_null
          - unique

      - name: eta_timestamp
        description: "Estimated time of arrival (ETA) as a timestamp"
        tests:
          - not_null

      - name: type
        description: "Ship type code"
        tests:
          - not_null

      - name: vessel_type
        description: "Ship type description from external catalog"

      - name: vessel_group
        description: "Ship group classification from external catalog"

      - name: latitude
        description: "Reported latitude"
        tests:
          - not_null

      - name: longitude
        description: "Reported longitude"
        tests:
          - not_null
