version: '3.1'
services:
postgres_data:
  image: postgres:15.4-alpine # change image
  volumes:
    - ${PWD}/include/postgres:/var/lib/postgresql/data # change volume
  networks:
    - airbyte-net
  ports:
    - 5433:5432
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  extra_hosts:
    - "host.docker.internal:host-gateway" # check this
