maritime_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_DESTINATION_HOST') }}"
      user: "{{ env_var('POSTGRES_DESTINATION_USER') }}"
      password: "{{ env_var('POSTGRES_DESTINATION_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_DESTINATION_PORT') | int }}"
      dbname: postgres
      schema: public
      threads: 1
